### ISSUE TITLE
https://docs.astronomer.io/v2/apache_airflow/sources-and-destinations.html is out of date

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#124]

**Comment by petedejoy** [comment]
@ryw Is this what I should be working from to keep them up to date? https://github.com/airflow-plugins

**Comment by ryw** [comment]
Yes - maybe setup a weekly task to check

**Comment by petedejoy** [comment]
Will do. I'll check and update every Monday morning. I'm also updating our `Hooks` and `Operators` docs to reflect all changes.

**Comment by petedejoy** [comment]
@ryw What do you think about restructuring docs so that `Hooks` and `Operators` drop down directly into separate pages for the hooks/operators we have built out (similar to the way sources/destinations drop down in clickstream)? Currently, all of our hooks and operators are piled into large and hard-to-navigate docs that will only get larger as we add to the library.

**Comment by ryw** [comment]
if you think it improves user experience, I'm down - maybe cross-link pages

**Comment by petedejoy** [comment]
Cool, I'll play around with it today and let you know when it's deployed. Closing this for now, opening up a separate issue for the structural changes.
