### ISSUE TITLE
Code blocks aren't displaying correctly in Airflow docs

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/documentation#130]
It's showing up correctly in markdown, so I'm not sure why it's wrong on the docs site. Looking into it now.

**Comment by petedejoy** [comment]
Happening in GA to S3, Facebook Ads to S3, and IMAP to S3 operator docs.

**Comment by petedejoy** [comment]
@tedmiston I know you mentioned that you might be able to look into this- it looks like changing double quotes to single quotes in the code blocks partially fixed the problem (ie. https://docs.astronomer.io/v2/apache_airflow/operators/imap-to-s3.html). However, there are still issues in docs with no quotes (ie. https://docs.astronomer.io/v2/apache_airflow/operators/google-analytics-to-s3.html). The code is rendering properly in VScode and in the respective github files, so I can't seem to figure out why it's not rendering properly on the live site. Not urgent, but let me know if you have any thoughts.

**Comment by tedmiston** [comment]
@petedejoy I dug into this and figured it out.  This was actually a problem with all code blocks across the docs site.

As far as quotes, we shouldn't change the quotes in the code because `"""` vs `'''` has different semantics in Python.  Docstrings use `"""` by convention.

The root problem is that Markdown, unlike programming languages, doesn't have one standard that everyone implements.  So sometimes you see rendering differences across tools because of the different "flavors".

On the docs site, it looks like we're using GitHub Flavored Markdown (GFM) via the `kramdown` Markdown engine in Jekyll.

https://github.com/astronomerio/documentation/blob/e057c5d2cc0331a11dfabf47b0e50a7609fd4c4e/_config.yml#L55-L60

But kramdown is a superset of markdown with its own code block syntax:

```
~~~ ruby
def what?
  42
end
~~~
```

https://kramdown.gettalong.org/quickref.html#code-blocks

For inline code it uses the normal backtick syntax.

https://kramdown.gettalong.org/quickref.html#inline-code

Triple backticks appeared to be working on some parts of the docs site with language name, but I don't think it was working correctly behind the scenes.  I think there's an obscure bug (https://github.com/jekyll/jekyll/issues/4448, https://github.com/jekyll/jekyll/issues/2709) in the version of Ruby or kramdown that we're using with the normal Markdown syntax.  The dockerfile in our repo looks like it was forked from [mrafayaleem/documentation-theme-jekyll](https://github.com/mrafayaleem/documentation-theme-jekyll) with old versions.

For now, let's just work with the kramdown block syntax in their docs.

I fixed one snippet on master as a test, and am sending a PR your way that fixes all of the code blocks site wide.  I also made some other syntax clean up changes / fixes in separate commits so you can see them easily.

Later we can modify and update the dependencies _or replace it with python_. 😎

**Comment by tedmiston** [comment]
PR sent - https://github.com/astronomerio/documentation/pull/151

Leaving this in review until merged

**Comment by tedmiston** [comment]
looks good in prod - done
