### ISSUE TITLE
Patch up Webhooks Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#133]
**Helpful Links-**

[Current Docs](https://docs.astronomer.io/v2/clickstream/destinations/webhooks.html#getting-started-with-webhooks-and-astronomer-clickstream)

[Segment](https://segment.com/integrations/webhooks)

[Segment GH Example](https://github.com/segmentio/webhooks-example)

**Comment by tedmiston** [comment]
@paolaperaza I was working on webhooks code / config today, so thought I'd touch up their docs a bit as well.  Just sent you a PR that should help with this.

https://github.com/astronomerio/documentation/pull/138

I noticed the Segment sample code is JS / Express.  If you think it's useful, we could also provide a simple Python webhook example as an alternative since our userbase is more familiar with it.

**Comment by paolaperaza** [comment]
@tedmiston getting back to this - thanks for those edits. I definitely think it'd be helpful to have that Python webhook example in there. 

Do you have sample code already we could use?

**Comment by tedmiston** [comment]
Sorry - missed this reply.  We don't have any sample code prewritten today but any of our python devs could do it.

**Comment by ryw** [comment]
closing this, taylor fixed up to some degree, and i don't think we need to build a sample app
