### ISSUE TITLE
Add instructions for Fortinet appliances to "Setting Up VPN Tunnel" page

### ISSUE THREAD

**Issue by ryw** [astronomerio/documentation#50]
@ryw commented on [Wed Sep 27 2017](https://github.com/astronomerio/customer/issues/178)

@benjamingregory commented on [Mon Jul 31 2017](https://github.com/astronomerio/astronomer-docs/issues/114)

**Comment by sammf** [comment]
This isn't customer facing documentation, since we don't currently allow customers to setup their own VPN connections? 

@abrongersma - Does engineering track this type of documentation anywhere? If so, can you move this issue to that repo? If this isn't relevant anymore, feel free to close out this task.

**Comment by abrongersma** [comment]
It would be best to place this in the engineering wiki.
