### ISSUE TITLE
Server Side

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#6]
Current table of contents:

- Getting Started with Server-Side Sources
- HTTP API
- MeteorJS
- Node.js

**Comment by beckysteele** [comment]
@petedejoy Do you have a link to an open pull request that I can review? Are there changes waiting in a branch somewhere?

**Comment by petedejoy** [comment]
@beckysteele Forgive my ignorance, but I was thinking that we'd just work off of the test site (https://astronomerio.github.io/documentation/). Is there an easier way to do it?

**Comment by beckysteele** [comment]
Nice job with Server Side! It's so great to see this taking shape :)

A few suggestions/recommendations:

- As a user, when I click a link in the tree and get redirected down the page, and then want to go back up to the tree by hitting the back button in the browser, I'm taken back to the last URL I visited, not the tree at the top of the page. Recommendation: give the user some easy way of getting back up to the selection tree from further down the page, so they don't have to scroll all the way up.

(Okay, on to the technical stuff)

In the HTTP API section: https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#http-api
- Change `app_ID` to `Source ID` to be consistent with the UI for creating a new server side source.
- (ignore if this is coming later) Is there an example we can show of how to set the `content-type` header, or do the Basic Auth? I've set up and used the HTTP API once, and it may have been a result of me being a novice with HTTP Auth, but it took me a while to figure out how to set up `authentication` and `content-type` correctly. An example could go a long way in helping the user get started.

In the Node.js section:

- Update the JavaScript in [Step 2](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#step-2) to be compliant with ES6, using `import` instead of `require`. See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
- Also in Step 2, fix typo in `Initialize this package with teh App ID` and change `App ID` to `Source ID` to be consistent with the UI.
- In [Step 3](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#step-3), missing a space in this chunk of text: `methods(identify, track, etc.)`
- In [Calls in Node.js](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#calls-in-nodejs), there's a reference to checking out our Calls section, but no link to it. Recommendation: add the link to it.

In the PHP section:
- In [Step 3](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#step-3-1), change `App ID` to `Source ID` to be consistent with the UI.
- In [Calls in PHP](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#calls-in-php), there's a reference to checking out our Calls section, but no link to it. Recommendation: add the link to it.

In the Python section:
- In [Step 2](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#step-2-2), change `App ID` to `Source ID` to be consistent with the UI.
- (for when this gets finished) In [Calls with Python](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#calls-in-python---not-done), there's a reference to checking out our Calls section, but no link to it. Recommendation: add the link to it.

In the Ruby section: 
- In [Step 2](https://astronomerio.github.io/documentation/v2/clickstream/sources/serverside.html#step-2-3),  change `App ID` to `Source ID` to be consistent with the UI, but only in the description and not in the code snippet or you'll breaky breaky.

**Comment by petedejoy** [comment]
@beckysteele Thank you so much. Since we're working on getting the docs MVP out by EOD today, I'm going to assign issues for the navigation suggestion and BasicAuth example and get to them later this week/early next week. All the other changes have been made and I'm working to finish up the Python, Meteor, and Ruby sections by EOD today.

**Comment by beckysteele** [comment]
Sounds great! Nice job!
