### ISSUE TITLE
Amazon Redshift

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/documentation#9]

**Comment by paolaperaza** [comment]
v.1 draft good to go. Passing off to @beckysteele for an initial review!

**Comment by beckysteele** [comment]
@paolaperaza Do you have a link to an open pull request that I can review? Are there changes waiting in a branch somewhere?

**Comment by beckysteele** [comment]
This looks great!

In the Getting Started with Amazon Redshift section:
- There's a typo in the third paragraph, here: `ETL (Exract - Transform - Load)`
- (this one is a sanity check) In the third paragraph, we say... `and then inserts structured event data from our bucket into your Redshift cluster.` At one point, we copied event data from S3 to the customer's Redshift. It's worth confirming with engineering that we do in fact insert and not copy (there's a difference).

In [Step 1](https://astronomerio.github.io/documentation/v2/clickstream/destinations/amazon-redshift.html#step-1-pick-a-cluster-that-fits-your-needs):
- There's a note to move on to Step 3 if the user has already done this. Link to Step 3.
- In the second paragraph we reference a `track` call as `.track(_)`. While this is not wrong, it is inconsistent with other references we make to the `track` call, as `track` or `analytics.track()`. I recommend using whatever method call consistently throughout the docs, to make it clear to the user.
- Looks like something wonky happened with the Github header in this paragraph `#### Dense Compute Cluster Dense`

In [Confirm and Insert Credentials](https://astronomerio.github.io/documentation/v2/clickstream/destinations/amazon-redshift.html#confirm-and-insert-credentials):
- In the SQL command shown, does a user have to create a user called `segment`, or can they call it `astronomer`?  The answer might be `segment`, but I'm surprised that this is the case. Ignore this comment if I'm wrong after checking with engineering. If the user can be `astronomer`, I recommend changing that.

In [Step 4](https://astronomerio.github.io/documentation/v2/clickstream/destinations/amazon-redshift.html#step-4-activate-integration-on-astronomer):
- I recommend one of those fancy video screen shots instead of the text instructions for setting up the UI.

**Comment by paolaperaza** [comment]
Everything fixed, but we still need to add a GIF animation for the UI set-up. See [issue #90](https://github.com/astronomerio/documentation/issues/90)
